### ISSUE TITLE
Create JSON APIs

### ISSUE THREAD

**Issue by jenphillips** [gmcquillan/firetower#5]
Right now the error data is sent to the front end by populating a page template variable - I think it would be more flexible/powerful to be able to make an ajax call that returns the json here.  (If nothing else, makes it easier for me - this is how I'm used to pulling in chart data.)  I'll take a stab at setting this up, if there are no objections.

**Comment by dcolish** [comment]
If you're going to start designing a rest api, give an overview of what the endpoints will look like before getting too far along.

**Comment by gmcquillan** [comment]
I think having a REST API, and/or returning JSON to the frontend is a fine idea. I agree with Dan, though. If we're going to build any kind of API expose this information, we should consider the design carefully. 

Jen, as someone who wants to use this for different pieces of information within your own infrastructure, do you want to take a stab at this? It'd be cool to not have a bunch of bias from me (especially) concerning what's useful and what's not.

**Comment by schmichael** [comment]
@dcolish: It's on a white board here at UA :)

Niall pointed out one little problem with the REST API Jen & I came up with:

/api/categories/`<category_id>`/ returns a timeseries whereas:
/api/categories/`<category_id>`/events returns the raw events.

So we should create a sub-resource for returning the timeseries:

/api/categories/`<category_id>`/timeseries

Not a great name, but it should do.

Then both sub-resources (timeseries & events) accept a number of GET query parameters to filter the data they return:

start=`<UNIX timestamp>`
end=`<UNIX timestamp>`

Eventually for timeseries we'll want parameters like:

moving_average=`<int>`
granularity=`<int>` (right now 1s)

Edit: switched all &lt; and &gt; signs to [] because github sucks.
Edit 2: Learn me some Github markdown

**Comment by schmichael** [comment]
fwiw I told Jen how to configure git wrong, so we never meant to commit this directly to upstream. In the future we'll go the standard route of committing to private repos/branches and sending pull requests to facilitate better discussion.

**Comment by dcolish** [comment]
Pics of whiteboard pls!

Anyway, I'm just being pedantic about the mixing of query params and routing args early on before the API grows too much. Let's be careful how those mix. Not always are those two great tastes that taste great together.

**Comment by schmichael** [comment]
@dcolish: The general idea is to represent the underlying data structures with RESTful resources (categories at first), general views of those resources with sub-resources (events, timeseries), and query parameters as ... query parameters (start, end, granularity, moving average, etc).

I'm pretty sure the whiteboard is far less useful than that description, but here you go: http://i.imgur.com/V6aqS.jpg

**Comment by dcolish** [comment]
lol :)

OK, I can buy into that design for urls. What sort of input values will be accepted for, lets say, start/end?

**Comment by schmichael** [comment]
Being a neckbeard I default to UNIX timestamps, but w/e works easiest. Second granularity is probably ideal.

**Comment by dcolish** [comment]
The neck beard in me says awesome, the user in me wants types that are richer.

**Comment by gmcquillan** [comment]
Eh. This is a project for neckbeards. Since all of our underlying data is in epoch time, I don't see a reason to complicate the GET vars for URL hackability from the user's perspective, at least not yet.

**Comment by gmcquillan** [comment]
I have code for this (and all the categories simultaneously) posted in the archive_feature branch. They're using the category models which we'll be using for all programatic changes to the timeseries or event datasets going forward.
